service: HelloWorldService

provider:
  name: aws
  profile: michelin
  region: eu-west-1
  deploymentBucket: michelin-package

  runtime: nodejs4.3
  versionFunctions: false

  # Add permission to send message into the SQS
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:sendMessage"
      Resource:
        Fn::GetAtt:
          - "HelloWorldQueue"
          - "Arn"


functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: hello
          method: get
      - s3:
          bucket: jpi-event
          event: s3:ObjectCreated:*
    environment:
      OutputSQS:
        Ref: "HelloWorldQueue"

# Create SQS with cloudformation tpl
resources:
  Resources:
    HelloWorldQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "HelloWorld"
        MaximumMessageSize: 262144
    QueueDepthAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
          AlarmDescription: "Alarm if queue depth grows beyond 10 messages"
          Namespace: "AWS/SQS"
          MetricName: "ApproximateNumberOfMessagesVisible"
          Dimensions:
            - Name: "QueueName"
              Value:
                Fn::GetAtt:
                  - "HelloWorldQueue"
                  - "QueueName"
          Statistic: "Sum"
          Period: "60"
          EvaluationPeriods: "1"
          Threshold: "10"
          ComparisonOperator: "GreaterThanThreshold"
