Parameters:
  EcsClusterName:
    Type: String
    Description: ECS Cluster Name
  DockerImage:
    Type: String
    Description: Docker image to pull

  CloudWatchLogsRetentionInDays:
    Description: The number of days log events are kept in CloudWatch Logs
    Type: Number
    Default: 1
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]


Resources:
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '${EcsClusterName}-grafana'
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  Service:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref EcsClusterName
      DesiredCount: 1
      TaskDefinition: !Ref Task

  Task:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: jpinsolle-grafana
      Volumes:
      - Name: grafana-database
        Host:
          SourcePath: "/home/ec2-user/grafana-database"
      ContainerDefinitions:
      - Name: grafana
        Image: !Ref DockerImage
        Memory: 100
        PortMappings:
          - ContainerPort: 3000
            HostPort: 80
        Environment:
          - Name: GF_INSTALL_PLUGINS
            Value: jdbranham-diagram-panel,grafana-clock-panel,grafana-piechart-panel,briangann-gauge-panel,vonage-status-panel
        MountPoints:
          - SourceVolume: grafana-database
            ContainerPath: "/var/lib/grafana"

  RoleGrafana:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["ec2.amazonaws.com"]
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "cloudwatch"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "cloudwatch:*"
                Resource: "*"



Outputs:
  RoleGrafana:
    Description: Role to get activities
    Value: !GetAtt RoleGrafana.Arn
  Task:
    Value: !Ref Task
  LogGroup:
    Value: !Ref LogGroup
